version: '3'
services:
  nodejs-service:
    image: 282484137350.dkr.ecr.us-east-1.amazonaws.com/nodejs-app-repo:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    
